### ISSUE TITLE
[Issue]: Some games not working in 4.5.4 which were working in earlier versions

### ISSUE THREAD

**Issue by randomname42** [dborth/snes9xgx#1086]
### Describe the bug

Some games (for example Stunt Race FX and Bomberman 3) aren't working in 4.5.4 when they were in earlier versions. Stunt Race said a controller is needed and I don't remember what the other one did but neither will let you play in 4.5.4.

I downgraded to 4.5.3 and they worked like normal.

### To Reproduce

Load either game in 4.5.4

### Expected behavior

The games should run like normal not get stuck on some screen where you can't do anything.

**Comment by InfiniteBlueGX** [comment]
This is not a bug - you likely have the assigned controller set to one of the SNES mouse options. Those games will display a warning if it detects a connected SNES Mouse.

After you start a game, open the menu and go to Game Settings -> Controller, then set the controller option to "SNES Controllers (2)". 

After reproducing the behavior you described this allowed the games to be played as usual in v4.5.5. If that doesn't work for you please let me know, otherwise this issue can be closed.
