### ISSUE TITLE
Wii U/vWii GC adapter support

### ISSUE THREAD

**Issue by charburgx** [dborth/snes9xgx#681]
Nintendont supports it, and I believe this should as well.

(It also may be impossible due to the nature of the vWii, in which case please disregard this Issue)

**Comment by BenJuan26** [comment]
It's definitely not impossible. The problem is that the GC adapter exposes the GC controllers as regular USB HID devices instead of native GC controllers that the Wii knows what to do with. Since snes9x-gx was written for the original Wii, it only currently supports native GC controllers. I'm casually looking into how hard it would be to add HID controller support (this is what Nintendont does) but it would be much easier for someone actually familiar with this project.

**Comment by dborth** [comment]
If someone submits a pull request for this, I'll merge it in. Otherwise, it's not going to happen...
