### ISSUE TITLE
"fix joystick calculations"  issue

### ISSUE THREAD

**Issue by bladeoner** [dborth/snes9xgx#738]
With commit "fix joystick calculations" I'm experiencing the issue that when I connect a Super Nintendo controller in the nunchuck port of the wiimote that the cursor will keep scrolling up in both the rom selection menu as in the game.

I reverted the commit to be sure that was causing the issue, I expect it will be the same for FCEUGX and VBAGX.

I thought maybe this line cause it:
return (s8)(128.0 * ((float)pos / (float)(center - min)));

And changed it into:
return (s8)(-128.0 * ((float)pos / (float)(center - min)));

But that didn't work.

**Comment by dborth** [comment]
Is this only with your own build or does it also happen on the official build?

**Comment by bladeoner** [comment]
The problem also occurs with the official build, I think it has something to do with:

js = stick ? &wpad->exp.classic.rjs : &wpad->exp.classic.ljs;

**Comment by dborth** [comment]
Not sure what's going on for you. I don't hear other people complaining so I assume the logic works in "most" cases. The problem is the logic in wiiuse itself seems to have changed. And now we're supporting Wii U controllers which requires some changes. The code currently used is basically the same as:
https://github.com/ekeeke/Genesis-Plus-GX/blob/master/gx/gx_input.c

And also similar to:
https://github.com/mgba-emu/mgba/blob/master/src/platform/wii/main.c

I'm open to suggestions, but since it's working for me I have no way to know if any changes I make will fix your problem. If you come up with something I'd suggest posting a build on gbatemp and see if it also works for others.
