### ISSUE TITLE
A few problems have been identified with version 4.3.8 of snes9xgx.

### ISSUE THREAD

**Issue by ace10v2** [dborth/snes9xgx#741]
* I can't speak English. Even if it's hard to recognize, I hope you understand.

1. There is an error where the modified date of the save file is stored as 2026

2. Audio is turned off when using Fast Forward.

3. (I haven't enjoyed a variety of games yet.)
 I have intermittent freezing symptoms during the Legend of Zelda

**Comment by supersonicjc** [comment]
well if were just doing a grab bag, got to add that a few roms that worked prior in v 4.3.7 now don't run abet due to the going back to core 1.5.1 chou aniki no longer runs and as well as tengai makyou zero, both titles did work perfectly in v4.3.8 beta 4  so with that in mind its the dual core idea in the system, is there an easy way to switch to the new core of 1.5.6 which runs both titles on the pc perfectly?

**Comment by dborth** [comment]
1. This was a problem in a pre-release. It's no longer an issue.
2 and 3 are fixed.
