### ISSUE TITLE
Key combo exit not working on new release

### ISSUE THREAD

**Issue by filevans** [dborth/snes9xgx#845]
Hello,
I have been using version 4.3.6 and previously others before it, and to exit a game to the menu you could use key combo L+R+Y+X on the gamecube / snes controller, but now it won't work and am forced to use the Wiimote, can this be activated anywhere? If not I will stay using 4.3.6
do you know which version this feature was taken out? as I can't find it mentioned in the change log
thanks

**Comment by dborth** [comment]
It was removed, I think I forgot why it was there to begin with. I've added it back for the next release.

**Comment by bladeoner** [comment]
@filevans the code has been changed now to L+R+SELECT because you can easily press L+R+Y+X while playing fighting games.

**Comment by filevans** [comment]
L+R+select was not working for me either? also dborth the exit key combo won't work on fceultra gx either

**Comment by dborth** [comment]
It's been added back for both, you'll see it in the next release

**Comment by bladeoner** [comment]
@filevans to clarify things, dborth fixed the key combo for Snes9x GX when he send the first reply. But quickly after that I proposed to change the key combo to L+R+SELECT which if you use the standard input on the Gamecube controller L+R+Z I believe. In order to use it you need to compile it yourself, wait until the next release or keep an eye on the following thread since I upload new version which are between releases: https://gbatemp.net/threads/snes9x-gx-4-4-0-beta-feedback-requested.521929/

**Comment by filevans** [comment]
Well letting the user choose the key combo would be even better to save any issues further down the line. 

Could you add the key combo back into all of the gx emulators please like VBA gx as that's had exit key combo disabled too it seems, along with fce gx.

**Comment by filevans** [comment]
Hello is there a release available yet with the key combo back in?
