### ISSUE TITLE
240p Double Strike Mode?

### ISSUE THREAD

**Issue by fortofawesome35** [dborth/snes9xgx#909]
I was wondering if this emulator has a Double Strike Mode like Mednafen does? I'm using a CRT TV and I would like to play my games in it's original resolution instead of 480i.

**Comment by SirYodaJedi** [comment]
(Could've at least answered the simple yes or no question when closing it...)

No unfortunately, the so-called "original" mode is actually upscaled to 480i/576i instead of outputting the original 240p/288p, see issue #944 and #722. IDK if FCE Ultra GX has proper 240p support either (relevant: dborth/fceugx#20).
