### ISSUE TITLE
emulator wont remember last game played

### ISSUE THREAD

**Issue by supersonicjc** [dborth/snes9xgx#936]
**Describe the bug**
when first loading up the emulator it no longer remembers what the last game was played and instead it jumps from 10 to 20 games further up your game list

**To Reproduce**
boot up the emulator for the first time and what you should get is the last game that you played before turning the emulator off for the day, instead it jumps up on your game list
**Expected behavior**
the emulator should remember what the last game was before you closed the emulator down to be able to just jump back into the game that you were playing this was still working back in version 4.4.6 and hasn't worked on the last 2 revisions 
I did report this and it was shrugged off before but this is a bug that should be fixed please, the only work around im finding right now is that the newly rerelease channel app doesn't have this bug attached to it but the other 2 do
**Screenshots**

**Comment by dborth** [comment]
This is likely a timing issue because of a delay between when your device is mounted and ready and when the file browser starts up and tries to list/display the contents. I have absolutely no intention of looking at this. If someone else fixes it and makes a PR, this will be fixed. Otherwise it won't.

Please stop harassing me.
